import { Termek } from "./kategoria.type";

export const termekAdatok: Termek[] = [
    {
        nev: 'Professzionális körömreszelő',
        ar: 1200,
        mennyiseg: '1 db',
        kep: '/src/assets/korom_reszelo.jpg',
        leiras: 'Kiváló minőségű körömreszelő, amely tartós és könnyen használható.',
        kategoria: 'reszelo',
      },
      {
        nev: 'Körömreszelő szett',
        ar: 3000,
        mennyiseg: '5 db',
        kep: 'korom_reszelo.jpg',
        leiras: 'Többféle méretű és formájú körömreszelő egy praktikus szettben.',
        kategoria: 'reszelo',
      },
      {
        nev: 'Finom szemcsés reszelő',
        ar: 800,
        mennyiseg: '1 db',
        kep: 'finom_reszelo.jpg',
        leiras: 'Finom szemcsés reszelő a precíz munkához.',
        kategoria: 'reszelo',
      },
      {
        nev: 'Ívelt körömreszelő',
        ar: 1000,
        mennyiseg: '1 db',
        kep: 'ivelt_reszelo.jpg',
        leiras: 'Ívelt kialakítású reszelő a könnyebb használatért.',
        kategoria: 'reszelo',
      },
      {
        nev: 'Extra tartós körömreszelő',
        ar: 1500,
        mennyiseg: '1 db',
        kep: 'extra_tartos_reszelo.jpg',
        leiras: 'Hosszan tartó használatra tervezett körömreszelő.',
        kategoria: 'reszelo',
      },
    
      // Ecset
      {
        nev: 'Precíziós ecset',
        ar: 800,
        mennyiseg: '1 db',
        kep: 'ecset.jpg',
        leiras: 'Finom szálú ecset, amely tökéletes a részletes munkákhoz.',
        kategoria: 'ecset',
      },
      {
        nev: 'Gél lakk ecset',
        ar: 1200,
        mennyiseg: '1 db',
        kep: 'gel_lakk_ecset.jpg',
        leiras: 'Speciális ecset gél lakk felviteléhez.',
        kategoria: 'ecset',
      },
      {
        nev: 'Széles fejű ecset',
        ar: 1000,
        mennyiseg: '1 db',
        kep: 'szeles_ecset.jpg',
        leiras: 'Széles fejű ecset nagyobb felületekhez.',
        kategoria: 'ecset',
      },
      {
        nev: 'Díszítő ecset',
        ar: 900,
        mennyiseg: '1 db',
        kep: 'diszito_ecset.jpg',
        leiras: 'Kiválóan alkalmas apró minták készítéséhez.',
        kategoria: 'ecset',
      },
      {
        nev: 'Ecset szett',
        ar: 4000,
        mennyiseg: '5 db',
        kep: 'ecset_szett.jpg',
        leiras: 'Többféle méretű ecset egy praktikus szettben.',
        kategoria: 'ecset',
      },
    
      // Gél lakk
      {
        nev: 'Tartós gél lakk - Piros',
        ar: 2500,
        mennyiseg: '15 ml',
        kep: 'gel_lakk_piros.jpg',
        leiras: 'Hosszan tartó, élénk színű gél lakk, amely nem kopik le.',
        kategoria: 'gel_lakk',
      },
      {
        nev: 'Tartós gél lakk - Kék',
        ar: 2500,
        mennyiseg: '15 ml',
        kep: 'gel_lakk_kek.jpg',
        leiras: 'Hosszan tartó, gyönyörű kék színű gél lakk.',
        kategoria: 'gel_lakk',
      },
      {
        nev: 'Tartós gél lakk - Rózsaszín',
        ar: 2500,
        mennyiseg: '15 ml',
        kep: 'gel_lakk_rozsaszin.jpg',
        leiras: 'Hosszan tartó, elegáns rózsaszín gél lakk.',
        kategoria: 'gel_lakk',
      },
      {
        nev: 'Tartós gél lakk - Fekete',
        ar: 2500,
        mennyiseg: '15 ml',
        kep: 'gel_lakk_fekete.jpg',
        leiras: 'Hosszan tartó, intenzív fekete színű gél lakk.',
        kategoria: 'gel_lakk',
      },
      {
        nev: 'Tartós gél lakk - Fehér',
        ar: 2500,
        mennyiseg: '15 ml',
        kep: 'gel_lakk_feher.jpg',
        leiras: 'Hosszan tartó, tiszta fehér színű gél lakk.',
        kategoria: 'gel_lakk',
      },
    
      // Zselé
      {
        nev: 'Építő zselé - Átlátszó',
        ar: 3000,
        mennyiseg: '50 ml',
        kep: 'epito_zsele_atlatszo.jpg',
        leiras: 'Erős és tartós építő zselé átlátszó színben.',
        kategoria: 'zsele',
      },
      {
        nev: 'Építő zselé - Rózsaszín',
        ar: 3200,
        mennyiseg: '50 ml',
        kep: 'epito_zsele_rozsaszin.jpg',
        leiras: 'Természetes rózsaszín árnyalatú építő zselé.',
        kategoria: 'zsele',
      },
      {
        nev: 'Építő zselé - Fehér',
        ar: 3100,
        mennyiseg: '50 ml',
        kep: 'epito_zsele_feher.jpg',
        leiras: 'Tökéletes fehér színű építő zselé.',
        kategoria: 'zsele',
      },
      {
        nev: 'Építő zselé - Csillámos',
        ar: 3500,
        mennyiseg: '50 ml',
        kep: 'epito_zsele_csillamos.jpg',
        leiras: 'Csillámos hatású építő zselé különleges megjelenéshez.',
        kategoria: 'zsele',
      },
      {
        nev: 'Építő zselé - Nude',
        ar: 3300,
        mennyiseg: '50 ml',
        kep: 'epito_zsele_nude.jpg',
        leiras: 'Természetes nude árnyalatú építő zselé.',
        kategoria: 'zsele',
      },
    
// Porcelán
{
    nev: 'Porcelán por - Átlátszó',
    ar: 2500,
    mennyiseg: '30 g',
    kep: 'porcelan_por_atlatszo.jpg',
    leiras: 'Kiváló minőségű átlátszó porcelán por.',
    kategoria: 'porcelan',
  },
  {
    nev: 'Porcelán por - Fehér',
    ar: 2600,
    mennyiseg: '30 g',
    kep: 'porcelan_por_feher.jpg',
    leiras: 'Tökéletes fehér porcelán por a precíz munkához.',
    kategoria: 'porcelan',
  },
  {
    nev: 'Porcelán por - Rózsaszín',
    ar: 2700,
    mennyiseg: '30 g',
    kep: 'porcelan_por_rozsaszin.jpg',
    leiras: 'Természetes rózsaszín árnyalatú porcelán por.',
    kategoria: 'porcelan',
  },
  {
    nev: 'Porcelán folyadék',
    ar: 3500,
    mennyiseg: '100 ml',
    kep: 'porcelan_folyadek.jpg',
    leiras: 'Speciális porcelán folyadék a tökéletes eredményért.',
    kategoria: 'porcelan',
  },
  {
    nev: 'Porcelán ecset',
    ar: 2000,
    mennyiseg: '1 db',
    kep: 'porcelan_ecset.jpg',
    leiras: 'Kiváló minőségű ecset porcelán munkákhoz.',
    kategoria: 'porcelan',
  },

  // Gépek
  {
    nev: 'Körömcsiszoló gép',
    ar: 15000,
    mennyiseg: '1 db',
    kep: 'koromcsiszolo_gep.jpg',
    leiras: 'Professzionális körömcsiszoló gép több sebességfokozattal.',
    kategoria: 'gep',
  },
  {
    nev: 'UV lámpa',
    ar: 12000,
    mennyiseg: '1 db',
    kep: 'uv_lampa.jpg',
    leiras: 'Gyors és hatékony UV lámpa gél lakkhoz.',
    kategoria: 'gep',
  },
  {
    nev: 'LED lámpa',
    ar: 14000,
    mennyiseg: '1 db',
    kep: 'led_lampa.jpg',
    leiras: 'Modern LED lámpa a gyors száradáshoz.',
    kategoria: 'gep',
  },
  {
    nev: 'Porelszívó gép',
    ar: 18000,
    mennyiseg: '1 db',
    kep: 'porelszivo_gep.jpg',
    leiras: 'Hatékony porelszívó gép a tiszta munkakörnyezetért.',
    kategoria: 'gep',
  },
  {
    nev: 'Elektromos reszelő',
    ar: 20000,
    mennyiseg: '1 db',
    kep: 'elektromos_reszelo.jpg',
    leiras: 'Professzionális elektromos reszelő több tartozékkal.',
    kategoria: 'gep',
  },

  // Bőrápolás
  {
    nev: 'Kézkrém - Aloe Vera',
    ar: 1500,
    mennyiseg: '100 ml',
    kep: 'kez_krem_aloe_vera.jpg',
    leiras: 'Hidratáló kézkrém aloe vera kivonattal.',
    kategoria: 'borapolas',
  },
  {
    nev: 'Kézkrém - Kamilla',
    ar: 1400,
    mennyiseg: '100 ml',
    kep: 'kez_krem_kamilla.jpg',
    leiras: 'Nyugtató kézkrém kamilla kivonattal.',
    kategoria: 'borapolas',
  },
  {
    nev: 'Bőrradír',
    ar: 2000,
    mennyiseg: '50 ml',
    kep: 'borradir.jpg',
    leiras: 'Gyengéd bőrradír a sima és puha bőrért.',
    kategoria: 'borapolas',
  },
  {
    nev: 'Kézápoló szett',
    ar: 5000,
    mennyiseg: '1 szett',
    kep: 'kezapolo_szett.jpg',
    leiras: 'Komplett kézápoló szett minden bőrtípusra.',
    kategoria: 'borapolas',
  },
  {
    nev: 'Körömágy olaj',
    ar: 1200,
    mennyiseg: '15 ml',
    kep: 'koromagy_olaj.jpg',
    leiras: 'Tápláló körömágy olaj a hidratált bőrért.',
    kategoria: 'borapolas',
  },

  // Kiegészítők
  {
    nev: 'Körömreszelő tartó',
    ar: 800,
    mennyiseg: '1 db',
    kep: 'koromreszelo_tarto.jpg',
    leiras: 'Praktikus körömreszelő tartó.',
    kategoria: 'kiegeszito',
  },
  {
    nev: 'Körömmatrica szett',
    ar: 1500,
    mennyiseg: '10 db',
    kep: 'korommatrica_szett.jpg',
    leiras: 'Kreatív körömmatricák különböző mintákkal.',
    kategoria: 'kiegeszito',
  },
  {
    nev: 'Körömdíszítő kövek',
    ar: 2000,
    mennyiseg: '1 szett',
    kep: 'koromdiszito_kovek.jpg',
    leiras: 'Színes körömdíszítő kövek a különleges megjelenésért.',
    kategoria: 'kiegeszito',
  },
  {
    nev: 'Körömápoló ecset',
    ar: 1000,
    mennyiseg: '1 db',
    kep: 'koromapolo_ecset.jpg',
    leiras: 'Speciális ecset a körömápoláshoz.',
    kategoria: 'kiegeszito',
  },
  {
    nev: 'Körömápoló szett',
    ar: 4000,
    mennyiseg: '1 szett',
    kep: 'koromapolo_szett.jpg',
    leiras: 'Komplett körömápoló szett minden igényhez.',
    kategoria: 'kiegeszito',
  },

];